# EurekaServer Application Properties

spring.application.name = EUREKA-SERVER

server.port = 8761
logging.level.org.springframework.web = INFO

# stopped devtools features
#spring.devtools.restart.enabled = false
#spring.devtools.livereload.enabled = false
#spring.devtools.livereload.port = 35735

eureka.client.register-with-eureka = false
eureka.client.fetch-registry = false
